# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 0702hjj

"""On-demand materialization for historical big versions —— 单一源（W-0059）。

ifc/cad 两侧原 ``app/ifc_materialize.py`` / ``app/dxf_materialize.py`` 是逐行
镜像的成对复制，本模块收编为按 ``ext`` 参数化的单点实现；服务侧只留薄 shim
（partial 绑定 ``ext`` + ``runner``），模块路径与 ``materialize_version``
签名不变（routes_diff 注入与 lazy_materialize 测试的调用 seam 不受影响）。

Only the latest big version keeps a materialized product under ``versions/``;
older snapshots are rebuildable cache, regenerated by sandbox-running their
script (``scripts/v{n}.py`` — the source of truth) into
``models/{id}/{ext}_cache/v{n}.{ext}``. The cache is a rebuild accelerator,
not state: entries are evicted LRU (oldest mtime first) past ``CACHE_MAX``
and can always be regenerated.

Determinism caveat: IFC rebuilt bytes differ from the original snapshot (IFC
header timestamps — only semantic equality holds, uuid5 GlobalIds), while DXF
rebuilds are semantically identical (the inner runner resets flows state, so
XDATA key counters restart per run). Consumers on both sides must compare via
each service's ``compute_diff``, never byte equality.
"""

from __future__ import annotations

import os
import threading
from typing import Any, Optional

from . import script_versions, versions
from .config import Settings

CACHE_MAX = 4


def cache_dir(data_dir: str, model_id: str, ext: str) -> str:
    return os.path.join(data_dir, "models", model_id, f"{ext}_cache")


def _evict_cache(cache_dir: str, ext: str) -> None:
    """Keep at most CACHE_MAX v{n}.{ext} files, evicting oldest by mtime."""
    pattern = versions.version_file_re(ext)
    entries = [
        name
        for name in os.listdir(cache_dir)
        if pattern.match(name)
    ]
    if len(entries) <= CACHE_MAX:
        return
    entries.sort(key=lambda name: os.path.getmtime(os.path.join(cache_dir, name)))
    for name in entries[: len(entries) - CACHE_MAX]:
        os.remove(os.path.join(cache_dir, name))
        sidecar = os.path.join(cache_dir, name + ".map.json")
        if os.path.exists(sidecar):
            os.remove(sidecar)


def _discard_partial(*paths: str) -> None:
    """失败清理：尽力移除中断可能留下的 tmp 产物/sidecar（不存在即跳过）。"""
    for path in paths:
        try:
            os.remove(path)
        except FileNotFoundError:
            pass


def materialize_version(
    data_dir: str,
    model_id: str,
    version: str,
    settings: Settings,
    *,
    ext: str,
    runner: Any,
) -> str:
    """Return a product path for a big version, rebuilding from script if needed.

    Order: existing ``versions/v{n}.{ext}`` snapshot → existing cache entry →
    sandbox re-run of ``scripts/v{n}.py`` into the cache. Raises
    FileNotFoundError when neither snapshot nor script exists; the sandbox
    run's HTTPException(422) propagates when the rebuild itself fails.

    ``runner`` 是服务侧 ``app.script_runner`` shim 模块对象——``run_script``
    在调用时解析属性，保住测试在 ``app.script_runner`` 上的 monkeypatch
    seam（与 deps.py 的 call-time 纪律同构）。

    重建产物先落同目录唯一 tmp（写者 pid+线程 id，W-0036/W-0037 同范式），
    成功后 ``os.replace`` 原子发布（W-0038）：tmp 与最终路径同目录（同卷）
    保证 replace 原子；run 中断/失败时半截产物至多停在 tmp，最终缓存路径
    不存在，不会被后续请求当合法命中。
    """
    snapshot = versions.version_path(data_dir, model_id, version, ext=ext)
    if snapshot is not None:
        return snapshot
    script = script_versions.script_path(data_dir, model_id, version)
    if script is None:
        raise FileNotFoundError(f"no snapshot or script for version: {version}")

    cache_root = cache_dir(data_dir, model_id, ext)
    cached: Optional[str] = os.path.join(cache_root, f"{version}.{ext}")
    if os.path.isfile(cached):
        os.utime(cached)  # LRU：命中刷新 mtime
        return cached

    os.makedirs(cache_root, exist_ok=True)
    with open(script, "r", encoding="utf-8") as fh:
        script_text = fh.read()
    # 唯一 tmp 名：并发写者互不覆盖对方的在写 tmp（共享名会让一方 replace
    # 掉另一方的半截文件）。run 侧自身也 tmp+replace（aibim_sandbox.runner 的
    # dest_tmp），此处再包一层使物化契约不依赖 runner 内部实现。
    tmp = f"{cached}.{os.getpid()}.{threading.get_ident()}.tmp"
    try:
        runner.run_script(settings, script_text, tmp, map_out=None)
        os.replace(tmp, cached)
    except BaseException:
        _discard_partial(tmp, tmp + ".map.json")
        raise
    # map sidecar 随产物换位配对（run 的 map_out=None 落在 tmp 旁）；本次无
    # sidecar 时清旧防错位（镜像 aibim_sandbox.runner 的清理语义）。
    sidecar_tmp, sidecar_dest = tmp + ".map.json", cached + ".map.json"
    if os.path.isfile(sidecar_tmp):
        os.replace(sidecar_tmp, sidecar_dest)
    elif os.path.exists(sidecar_dest):
        os.remove(sidecar_dest)
    _evict_cache(cache_root, ext)
    return cached
